[package]

name = "spellck"
version = "0.2.0"
authors = [ "Huon Wilson <dbau.pp@gmail.com>" ]

[lib]

name = "spellck"
path = "src/spellck/lib.rs"
plugin = true

[[bin]]

name = "spellck_standalone"

[dependencies.stem]
git = "https://github.com/mrordinaire/rust-stem"
