[package]

name = "spellck"
version = "0.2.0"
authors = [ "Huon Wilson <dbau.pp@gmail.com>" ]

[[lib]]

name = "spellck"
path = "src/spellck/lib.rs"
crate_type = ["dylib"]

[[bin]]

name = "spellck_standalone"
